-- MySQL Script generated by MySQL Workbench
-- Fri Oct 24 22:49:48 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema planaltovistoria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema planaltovistoria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `planaltovistoria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `planaltovistoria` ;

-- -----------------------------------------------------
-- Table `planaltovistoria`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `planaltovistoria`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `senha` VARCHAR(100) NULL DEFAULT NULL,
  `cpf` VARCHAR(14) NULL DEFAULT NULL,
  `tipo` ENUM('CLIENTE', 'FUNCIONARIO') NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `planaltovistoria`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `planaltovistoria`.`funcionario` (
  `idFuncionario` INT NOT NULL,
  `cargo` ENUM('VISTORIADOR', 'CONTABIL', 'GERENTE') NULL DEFAULT NULL,
  PRIMARY KEY (`idFuncionario`),
  CONSTRAINT `funcionario_ibfk_1`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `planaltovistoria`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `planaltovistoria`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `planaltovistoria`.`pagamento` (
  `idPagamento` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `status` ENUM('PENDENTE', 'PAGO') NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idPagamento`),
  INDEX `idCliente` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `pagamento_ibfk_1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `planaltovistoria`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `planaltovistoria`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `planaltovistoria`.`veiculo` (
  `idVeiculo` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NULL DEFAULT NULL,
  `modelo` VARCHAR(100) NULL DEFAULT NULL,
  `placa` VARCHAR(10) NULL DEFAULT NULL,
  `ano` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idVeiculo`),
  INDEX `idCliente` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `veiculo_ibfk_1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `planaltovistoria`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `planaltovistoria`.`vistoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `planaltovistoria`.`vistoria` (
  `idVistoria` INT NOT NULL AUTO_INCREMENT,
  `idVeiculo` INT NULL DEFAULT NULL,
  `idFuncionario` INT NULL DEFAULT NULL,
  `dataHora` DATETIME NULL DEFAULT NULL,
  `status` ENUM('AGENDADA', 'REALIZADA') NULL DEFAULT NULL,
  PRIMARY KEY (`idVistoria`),
  INDEX `idVeiculo` (`idVeiculo` ASC) VISIBLE,
  INDEX `idFuncionario` (`idFuncionario` ASC) VISIBLE,
  CONSTRAINT `vistoria_ibfk_1`
    FOREIGN KEY (`idVeiculo`)
    REFERENCES `planaltovistoria`.`veiculo` (`idVeiculo`),
  CONSTRAINT `vistoria_ibfk_2`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `planaltovistoria`.`funcionario` (`idFuncionario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
